name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Download layer
        run: curl -Lso layer.txz https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-Container-Base.latest.x86_64.tar.xz
      - name: Build
        run: podman build -t ghcr.io/charles8191/rockycontainerimage/rocky:9 .
      - name: Push
        run: podman push ghcr.io/charles8191/rockycontainerimage/rocky:9
